using System;
using System.Collections.Generic;

namespace SutraPlusApp_DAL.Models
{
    public partial class CashBook
    {
        public long SrNo { get; set; }
        public DateTime? TranctDate { get; set; }
        public string? Prt { get; set; }
        public decimal? Debit { get; set; }
        public decimal? Credit { get; set; }
        public long? LedgerId { get; set; }
        public long? CompanyId { get; set; }
        public long EntrTp { get; set; }
        public long? PBlNo { get; set; }
        public string? InvNo { get; set; }
        public bool? ForBuy { get; set; }
        public long? VBlNo { get; set; }
        public long? KBlNo { get; set; }
        public DateTime? TrDt { get; set; }
        public long? QId { get; set; }
        public bool? AgPay { get; set; }
        public bool? Paid { get; set; }
        public bool? PcaSales { get; set; }
        public long? Chno { get; set; }
        public bool? Prcs { get; set; }
        public string? Inwrds { get; set; }
        public long? NewEntry { get; set; }
        public long? BatchNo { get; set; }
        public long? ChkNo { get; set; }
        public long? Slf { get; set; }
        public long? StkTrns { get; set; }
        public long? PrchRet { get; set; }
        public long? PrchReturn { get; set; }
        public long? SrInvNo { get; set; }
        public long? Gng { get; set; }
        public long? FarPay { get; set; }
        public long? Tp { get; set; }
        public long? EntryId { get; set; }
        public long? EditId { get; set; }
        public long? Jrnl { get; set; }
        public long? BnkId { get; set; }
        public long? AcPay { get; set; }
        public long? DdlPaid { get; set; }
        public long? DdlTp { get; set; }
        public long? DnNo { get; set; }
        public bool? IsGinningTds { get; set; }
        public bool? IsCommissionTds { get; set; }
        public long? ProductionDcNo { get; set; }
        public long? BatchId { get; set; }
        public long? StemlessBatchNo { get; set; }
        public long? TotalBags { get; set; }
        public double? TotalWt { get; set; }
        public long? BillNumber { get; set; }
        public long? OrgInv { get; set; }
        public DateTime? OrgDt { get; set; }
        public long? GinInvNo { get; set; }
        public string? Narration { get; set; }
        public long? ItId { get; set; }
        public long? TransType { get; set; }
        public double? ObQty { get; set; }
        public double? PurchaseQty { get; set; }
        public double? SrQty { get; set; }
        public double? FromPr { get; set; }
        public double? FromStkTrnsfrQty { get; set; }
        public double? SalesQty { get; set; }
        public double? ToPr { get; set; }
        public double? ShortageQty { get; set; }
        public double? ClosingStock { get; set; }
        public decimal? AverageRate { get; set; }
        public bool? IsMulti { get; set; }
        public double? TradingPq { get; set; }
        public double? TradingSq { get; set; }
        public decimal? SrBasicValue { get; set; }
        public decimal? SrTax { get; set; }
        public decimal? BasicValue { get; set; }
        public decimal? Packing { get; set; }
        public decimal? Hamali { get; set; }
        public decimal? WeighmanFee { get; set; }
        public decimal? AssoFee { get; set; }
        public decimal? TaxableValue { get; set; }
        public decimal? Vat { get; set; }
        public decimal? Commission { get; set; }
        public decimal? Cess { get; set; }
        public decimal? Others { get; set; }
        public decimal? Rndf { get; set; }
        public string? TypeInReg { get; set; }
        public decimal? TaxRate { get; set; }
        public long? Purpose { get; set; }
        public string? TranType { get; set; }
        public decimal? SalesBasicValue { get; set; }
        public decimal? TaxInSales { get; set; }
        public double? SalesWeight { get; set; }
        public decimal? SalesExpenses { get; set; }
        public string? TypeInSaleReg { get; set; }
        public decimal? TaxRateInSales { get; set; }
        public decimal? IsIgnore { get; set; }
        public decimal? VikriBastani { get; set; }
        public decimal? VikriPacking { get; set; }
        public decimal? VikriHamali { get; set; }
        public decimal? VikriWtf { get; set; }
        public decimal? VikriAsf { get; set; }
        public decimal? VikriTaxable { get; set; }
        public decimal? VikriVat { get; set; }
        public decimal? VikriCommission { get; set; }
        public decimal? VikriCess { get; set; }
        public decimal? VikriRndf { get; set; }
        public long? VikriBags { get; set; }
        public double? VikriWt { get; set; }
        public long? VikriBlNo { get; set; }
        public long? VMin { get; set; }
        public long? VMax { get; set; }
        public decimal? Sgst { get; set; }
        public decimal? Igst { get; set; }
        public decimal? Cgst { get; set; }
        public string? InTheBillOf { get; set; }
        public string? PartyInvoiceNumber { get; set; }
        public long? VochNo { get; set; }
        public string? Vochtype { get; set; }
        public long? DebitNoteNo { get; set; }
        public decimal? Csgt { get; set; }
        public long? CreditNoteNo { get; set; }
        public bool? IsLorryTds { get; set; }
        public int? ClosingEntry { get; set; }
        public long? ExportInvNo { get; set; }
        public int? Upl { get; set; }
        public long? VoucherTypeid { get; set; }
        public long? VoucherNumber { get; set; }
        public string? PartyInvoiceNo { get; set; }
        public string? PartyNameforNrtn { get; set; }
        public string? InvoiceNumber { get; set; }
        public string? PrintNumber { get; set; }
    }
}
